### ISSUE TITLE
EML format

### ISSUE THREAD

**Issue by CodingFu** [mscdex/node-imap#427]
Is there a way to fetch message and save it to EML format with all the fields?

(I want to grab raw IMAP response somehow)

**Comment by j3g** [comment]
hi mscdex!!! This is a great explanation along with the example you have in the README for writing the raw files. I looked over your code and naturally you already have the parsers for the mail format ... any suggestions of how I can read one of these raw files using your parser? possibly use a *file* input stream with the parser instead of a *network* input stream.
Thanks!
