### ISSUE TITLE
PIPE line IMAP commands

### ISSUE THREAD

**Issue by subbiwy** [mscdex/node-imap#442]
Hi,
Is there any interface to pipe line the  multiple IMAP commands with out waiting for the previous request response. As you know if IMAP commands are  pipelined we can save round-trip delay. 

Can you please help if there is such interface in imap node.js

**Comment by mscdex** [comment]
While the RFC allows pipelining under specific conditions, from my experience there are other situations (even sometimes dependent upon server IMAP implementations) that can cause problems because of how the server returns response data (e.g. having no way to match up response data with a particular pipelined request). For this reason all commands are queued up to ensure reliable operation.
