### ISSUE TITLE
exceptions thrown instead of callback called or error event emitted?

### ISSUE THREAD

**Issue by elephantjim** [mscdex/node-imap#479]
Say, I've been playing around with the library, and it's been very useful so far.

However, as I've encountered quirks of IMAP servers, I've noticed that some problem conditions result in different behavior in the library.  For instance, .connect and the methods it calls will .emit an 'error' event with an Error-class object.  On the other hand, .openBox will call the callback with the error as the first argument.

That's fine, and both are node-like.  But at other times, functions will throw Javascript exceptions.  Am I missing something: is there an easy way to catch exceptions in an async environment without resorting to domains or `process.on('uncaughtException', fooHandler)`?

**Comment by mscdex** [comment]
Exceptions are only thrown on problems that can be detected immediately before doing anything asynchronous (e.g. bad arguments). If you see otherwise, it's probably a bug.

**Comment by elephantjim** [comment]
Thanks for the quick reply!

I s'pose I'm confused: why not just call the callback with the error and let the caller handle it there?  Otherwise I have to handle errors in two places: in the callback and in a try/catch wrapper around the call, or in an event handler and in a try/catch wrapper.  That gets awfully repetitive.

Any suggestions for how to implement this cleanly in a client of the library?  The sample code in the readme is helpful, but it doesn't mention this issue.

**Comment by mscdex** [comment]
This method for error handling is the same as in node.js/io.js core. For example, if you call `fs.readFile()` with an explicit string encoding that is not valid, an exception will be thrown immediately.

So the only time you might wrap your function calls in a try-catch is if you are blindly passing user-supplied function arguments. Otherwise if you are calling it with known, well-formed arguments or you are validating user-supplied arguments before calling the function, you should not worry about exceptions.
