### ISSUE TITLE
How can we safeguard against duplicates when downloading all emails?

### ISSUE THREAD

**Issue by jascination** [mscdex/node-imap#492]
I'm writing a script that downloads all of a user's sent and received emails.

The process is:

```
1. Get all box names
2. Loop through each box name and open said box
3. Download all the email from that box
```

In my own Gmail account, I have different labels set up (which are showing up as boxes in `node-imap`). In Gmail these emails still appear in my inbox, just with a label attached, and as far as I'm aware this happens when downloading from `node-imap` as well.

For each new message downloaded, is there a unique key within (or something else) that I can use to check whether it's already been downloaded from a different box? It's important I only have one instance of each message.

**Comment by mscdex** [comment]
The `[Gmail]/All Mail` mailbox *should* contain all of a user's sent and received emails that haven't been deleted. If that's what you're after, I think you may only need to open that mailbox.

As far as identifying messages goes, that can be tricky because UID is per-mailbox and `Message-ID` is optional (and if it does exist, uniqueness is not strictly enforced -- RFC says it *should* be unique). How the [`imapsync`](https://github.com/imapsync/imapsync) program uniquely identifies messages for example is it [hashes](https://github.com/imapsync/imapsync/blob/4a1d71d8fdab0706b0611e2257a817285ef8e1dd/imapsync#L5877) a [normalized](https://github.com/imapsync/imapsync/blob/4a1d71d8fdab0706b0611e2257a817285ef8e1dd/imapsync#L5897-L5951) version of the raw header of each message (using md5, but you could use whatever algorithm you want). So you could do something similar to more accurately ensure uniqueness.

**Comment by jascination** [comment]
Perfect, `[Gmail]/All Mail` did the trick
