### ISSUE TITLE
Fetching Email Body and parsing into plaintext

### ISSUE THREAD

**Issue by jascination** [mscdex/node-imap#493]
I'm fetching emails like so:

```
 imap.openBox(key, true, function(err, box) {
          var f = imap.seq.fetch('1:' + box.messages.total, {
              bodies: ['HEADER.FIELDS (FROM TO SUBJECT DATE)', 'TEXT'],
              struct: true
          });
          f.on('message', function(msg, seqno) {
              var obj = {};
              var prefix = '(#' + seqno + ') ';

              obj.num = seqno;

              msg.on('body', function(stream, info) {

                if (info.which === 'TEXT'){
                  console.log(prefix + 'Body [%s] found, %d total bytes', inspect(info.which), info.size);
                  var buffer = '', count = 0;
               }
              stream.on('data', function(chunk) {
                  count += chunk.length;
                  buffer += chunk.toString('utf8');
              });
              stream.once('end', function() {
                if (info.which !== 'TEXT'){
                  obj.header = Imap.parseHeader(buffer);
                }
                else{
                  obj.body = buffer;
                }
              });
            });
```

This works for the most-part, however a lot of my email bodies are coming out quite garbled. I've got ones that look like this:

```
--_000_HK2PR0301MB1123CA2C127329ED99A7266BD3AD0HK2PR0301MB1123_ Content-Type: text/plain; charset="utf-8" Content-Transfer-Encoding: base64 Tm8gcHJvYmxlbS4gSWwgc2VuZCB5b3UgYSBvbmUgcGFnZSAucGRmIEkgY2FtZSBhY3Jvc3MgdGhh dCBoZWxwcyBidXNpbmVzc2VzIGFzc2VzcyB0aGVtc2VsdmVzIHRvIGdldCBhIHBhcnRuZXJzaGlw LiBJdOKAmXMgb24gdGhlIHBjIGN1cnJlbnRseSBwdWxsZWQgYXBhcnQsIGJ1dCBpbCBnZXQgdG8g aXQgYmVjYXVzZSBJIG5lZWQgb3RoZXIgZmlsZXMgbG9sLiBUaGUgYmUgaG9uZXN0IEkgZGlkbuKA mXQgZXZlbiB1c2UgaXQsIGJ1dCBpdCB3aWxsIHByb2JhYmx5IGhlbHAgeW91IGFzIGl04oCZcyB ...<it goes on like this>
```

I've tried using `mimelib.decodeBase64(message)` and while this works to some extent, it leaves me with a lot of garbled characters like this at the end of my message

```
��[��H\��ۘ[��Z�HH�X�H���H[�\�X�[ۈ�\��\�H����K�x�&]�Hۙ��\H�[����[�Y\�[�HR��X�ܚ�����]\�H]8�&\�Hۛ�ۋ�Μ�H�[H\����[[��\�X\�\�[�\��\�[�\��
```

What's the best way to ensure that the message bodies I'm grabbing are in plain-text format before I store them to my database?

**Comment by mscdex** [comment]
The issue is that the email message has a multipart body and what you're seeing at the beginning of the `TEXT` part (the entire raw body) is the multipart boundary.

There's three ways to solve this:

* Fetch the email message structure *first* (`struct: true` for `fetch()`), then find the `partId` of the part you really want, and specify that string in your `bodies` array in `fetch()`. This can be more efficient since emails could contain very large attachments and this solution will avoid having to transfer any extra parts like that. So for example the `partId` for the `text/plain` part in your sample email may be `1` or `1.1` (depending on the body layout). FWIW there is a helper function [here](https://gist.github.com/mscdex/cbf8ce5f029783991a4a) that grabs the first `text/plain` or `text/html` part of a message by UID. Feel free to use it as-is or tweak it to fit your needs.

* Transfer the `TEXT` (the entire raw body) part along with the extra `Content-Type` header field (which contains the boundary) and use some multipart parsing module on npm using the boundary information and the `TEXT` part

* Transfer the entire email message by specifying an empty string in `bodies` for `fetch()` and use some mime/multipart module on npm to automatically parse the boundary and the body.

**Comment by jascination** [comment]
Thanks for the thorough response mate. Is there any guide to how the body layouts may be structured? How am I supposed to know what which part of the body is the actual sent/received message (1 or 1.1 or 1.2 or what)?

**Comment by mscdex** [comment]
There are a couple of examples in the [readme](https://github.com/mscdex/node-imap#data-types) that show what properties are available on message structure objects.

**Comment by jascination** [comment]
Got it. With your helper function, it seems a little incomplete - is `msguid` returned from first fetching a list of all emails in a box? Confused as to where I get the UIDs from.

Ugh, gotta say I've been struggling with this one for a couple of hours so apologies for asking for help. Here's a gist of where I'm at after playing with your code:

https://gist.github.com/jascination/85719030bf4b9abc7203

Getting pretty much nowhere with this though. This correctly opens a box and gets a list of emails with UIDs, I put them into your function and is returning bodies - but it's INCREDIBLY slow. Fetching all email parts at once was about 100x quicker (I'm talking over a minute to return 50 emails).

I assume I've messed up somewhere with the `fetch()` functions, can you take a quick look and see where I've gone wrong here?

**Comment by mscdex** [comment]
As far as performance goes, it could be the server throttling your requests. Also, it appears you're making the same request twice: Your code is fetching the `struct` once and then `getMsgByUID()` fetches it again. You can reduce the number of requests by only doing it once by modifying one place or the other appropriately.
