### ISSUE TITLE
break up FETCHes into batches

### ISSUE THREAD

**Issue by elephantjim** [mscdex/node-imap#518]
In our application, we SEARCH for messages we haven't seen yet, and turn around and FETCH envelopes for those messages.  We search and fetch by UID.

When connecting to Hotmail, it seems like the server simply hangs up when FETCHing too many messages at once.  That is, it doesn't give a "BAD" response.  It simply responds with "BYE" and hangs up.  See https://gist.github.com/elephantjim/4caabc1f2be48e0cbcd9 for a sample trace.  Not sure how often this is happening because of the unexpected hangup.  (There is no error so our system wasn't originally flagging it as such; it thought the hangup was a transient network issue and just kept retrying.)

As a workaround, we can break the FETCH into batches.  It would be nice, though, if the library did this automagically so we don't have to.  Is this a feature you'd consider?

**Comment by mscdex** [comment]
This problem is server implementation-specific and isn't something defined by an IMAP RFC. Some servers even allow you to configure the maximum command length, so that makes it even more difficult to come up with a good value to use.

Also I'm not typically a fan of automagic behavior like this, so I'd have to say I'm -1 on it.

**Comment by elephantjim** [comment]
Ok, fair 'nuf.  Just thought I'd make you aware of the non-compliant behavior.
