### ISSUE TITLE
When use SINCE in search function the email cannot be search out when replied already

### ISSUE THREAD

**Issue by johnzhou2011** [mscdex/node-imap#528]
When use SINCE in search function the email cannot be search out when replied already
ENV: Microsoft Exchange server.

**Comment by mscdex** [comment]
I'm not sure I understand what you mean by "when replied already." Is there an actual error message or are there just no search results?

Is the problem limited to particular messages? Is this perhaps a timezone issue? `SINCE` and other date-related search filters typically use the internal date stored by the server, which may/may not be UTC if I understand the IMAP specification correctly.

**Comment by johnzhou2011** [comment]
the result sort by received Date when using SINCE?

**Comment by mscdex** [comment]
If your server supports the SORT extension (RFC5256), you can get sorted search results using `imap.sort()`. See the [Extensions supported](https://github.com/mscdex/node-imap#extensions-supported) section for more information. You can explicitly check for extension support via `imap.serverSupports('SORT');` before trying to use the `imap.sort()` method.

**Comment by johnzhou2011** [comment]
ok thank you
