### ISSUE TITLE
How to use SINCE on time level not just date level

### ISSUE THREAD

**Issue by johnzhou2011** [mscdex/node-imap#535]
check the code in Connection.js
` searchargs += modifier + criteria + ' ' + args[0].getDate() + '-'
                        + MONTHS[args[0].getMonth()] + '-'
                        + args[0].getFullYear();`

It is possible to update it on date-time level?

**Comment by mscdex** [comment]
The IMAP `SINCE` filter is not that granular and only works on dates.

**Comment by johnzhou2011** [comment]
Mailbox frequent disconnection, so I need check the status and use `start()` every five minute and scan whole day email again. Any idea about _Frequent disconnection_ or mark the email which scanned already?(add flag?)

**Comment by mscdex** [comment]
If you're simply checking for new messages (no matter what their flags/status currently are), you should be able to simply keep track of the last known `uidvalidity` value (from the mailbox) and the last uid in that mailbox. As long as the `uidvalidity` does not change between sessions, you can simply just do an `imap.search()` for `'lastKnownUID:*'` and it will return all messages since that last message. If you get search results back, save the largest uid for the next time you do a scan/search.

If you need to synchronize other things like flag changes and such, the server will need to support the `CONDSTORE` extension, which gives you a `modseq` value you can store to search by later on to find messages whose metadata had changed since that `modseq` value.

**Comment by johnzhou2011** [comment]
Thank you very much! :)
So `uidvalidity ` base on mailbox folder and self increment?

**Comment by mscdex** [comment]
`uidvalidity` itself doesn't have any particular meaning, you just need to make sure it's still the same value before you go to search on the last saved UID. If it's different, you cannot assume the UIDs in the mailbox are still the same (the IMAP specification says servers "should not" ever change this unless absolutely necessary so chances are it probably will never change, but it's best to be ready just in case).

So some pseudo-code might look like:

```
connect()
box = openbox()
if lastuidvalidity is empty or lastuidvalidity is not box.uidvalidity or lastuid is empty {
  lastuidvalidity = box.uidvalidity
  searchResults = search(since lastdate)
} else if lastuidvalidity is box.uidvalidity {
  searchResults = search(lastuid:*)
}
messages = fetch(searchResults)
lastuid = getLargestUID(messages)
lastdate = getLastDate(messages)
```

where `lastuidvalidity`, `lastuid`, and `lastdate` would be stored in some kind of permanent storage for use the next time you connect.

**Comment by johnzhou2011** [comment]
`lastuid = getLargestUID(messages)`
How to get `UID` freom  messages ? or just get the last `searchResults ` value as lastuid?

**Comment by mscdex** [comment]
A message's uid can be found in the attributes object passed to `attributes` event handlers for a message. You can see an examples of this in the readme.

You can't just pick the last message and use its uid as `lastuid` because the server and return messages in any order.

**Comment by johnzhou2011** [comment]
thank a lot! :)
