### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by hamzazer** [mscdex/node-imap#577]
Hi,

I think i found a problem in the authentication problem, it occur when the password contains the character "\\":

```javascript
{
    user: 'test@example.com',
    password: 'password\password',
    .......
}
```
###### Workaround (escape the "\\" char)
```javascript
{
    user: 'test@example.com',
    password: 'password\\password',
    .......
}
```

**Comment by mscdex** [comment]
This problem is not specific to this module, all JavaScript strings allow escape sequences. If the sequence is not known/valid (e.g. `\p`), it treats the following character as-is (removing the backslash in the process). However if you include a *valid* escape sequence like `\t` in a string such as `'toon\town'`, what you will instead end up with is something like `'toon    town'` (and not `'toontown'`).
