### ISSUE TITLE
parseHeader doesn't handle multiple participants well

### ISSUE THREAD

**Issue by hallamoore** [mscdex/node-imap#584]
When passed a 'to' header with multiple emails, `parseHeader()` returns all of the emails in one string.

For example, `parseHeader("To: a@example.com, b@example.com")` returns `{to: ["a@example.com, b@example.com"]}`, but I would expect it to return `{to: ["a@example.com", "b@example.com"]}`

**Comment by spang** [comment]
The array returned from `parseHeader()` is actually one element per instance of the header in the message, since there is no restriction on a particular header appearing more than once. I think `parseHeader()` is doing what it says on the tin in this case, in that it returns the value of every To: header. The caller than has to pass these results into something like `mimelib.parseAddresses()` to get an array of participant names and emails—but this is only the case for To/From/Cc/Bcc, and not other headers which may require different parsing.

Not clear to me that it'd make sense for `parseHeader()` specifically to detect what further parsing needs to be done on certain headers, but either way this could be more clearly documented as I'm sure more folks want to turn To: headers into a parsed array of emails. :)

**Comment by mscdex** [comment]
@spang Is correct, the goal of `parseHeader()` in this module is to do a simple parsing of the header (to allow the end user to avoid the intricacies of header formatting). If you find that you need something that takes semantics of the header values into account, you should use something that is dedicated to that task, such as the `mailparser` or similar modules on npm.
