### ISSUE TITLE
Fetch New Emails

### ISSUE THREAD

**Issue by johnbaird4085** [mscdex/node-imap#627]
I need a way to check for new emails since last run. I don't know if I should store the sequence number or the UID. I would think UID and I could use something like HighestLocalUID + ':*'. But what you pasted here:

https://github.com/mscdex/node-imap/issues/473

confused me. Especially the part "even if 559 is higher than any assigned UID value." I don't understand the meaning of that.

Does [UID]:* fetch all emails after that one?
Should I just use Seqno as a starting point so I can do SeqNo:* ?
Are UID's guaranteed to be sequential as in say the first email is 1, the next one will be 2 and so forth?

I tried reading the specs and to me it sounds like they are but I wanted confirmation. Surprisingly there are very few articles about IMAP integration.

**Comment by mscdex** [comment]
A simple way is to just search for unseen emails. Example:

```js
imap.search([ 'UNSEEN' ], (err, results) => {
  if (err) throw err;
  console.log(results.length, 'unread emails');
});
```

**Comment by johnbaird4085** [comment]
I can't use that because if they get say...10 emails while offline but read them on their phone, when my code runs it won't get them and looks weird. I know I could keep fetching and comparing until I get to one that exists locally but I was trying to do this the "right" way. 

Is using UID : * not possible?

**Comment by mscdex** [comment]
I don't understand what you're wanting then. Are you trying to synchronize *all* emails since the last connection? If so and the server supports `CONDSTORE`, then you can simply save the last `modseq` value and then on the next connection use the `changedsince` `fetch()` option with the last stored `modseq` value to get all changes since that point. See the RFC4551 section in the readme.

You cannot just search for `uid:*` because UIDs are only guaranteed to be unique, although some servers *may* use an incrementing only counter as this value, that is an implementation detail.

**Comment by johnbaird4085** [comment]
Okay thanks
