### ISSUE TITLE
How can i parse multiple parts TEXT use mimelib?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#630]
I am just want to parse the body part of an email like bellow.

` fetch('1:12', {bodies: 'TEXT', struct: true}).`

How can i handle it with multiple part body email?

Thanks

**Comment by mscdex** [comment]
You would need to fetch just the structures first and *then* fetch the bodies you need for each message.

You *could* group these `fetch()`s (by their `bodies`) together to be a little more efficient (instead of calling `fetch()` for every single message). For example if you have several messages that are not multipart, you could fetch just those messages with `bodies: 'TEXT'`. If you have several that you want just the first part then fetch just those with `bodies: '1.TEXT'`, etc. The numeric prefix you use is determined by the `partID` in the message's structure. See the description in the readme under the _ImapFetch_ data type for examples.

**Comment by quangvinh1305** [comment]
Hi @mscdex, 
Thank you for your answer. 
But i have an issue when i `fetch(uid, {bodies: ['1.TEXT' //html, '1.2TEXT' //PLAIN, '2.TEXT'//Attachment],  struct: true})` 10 times. i took about 0.25 seconds * 10 = 2 seconds.
`if (info.which === '1') 
     handle(html)
else if (info.which === '1.2')
   handle(text)
else if(info.which === '2')
  handle(attachment)
`

when i do like this ` fetch('1:12', {bodies: 'TEXT', struct: true})` i took about 0.35 seconds.
Do you have any ideals?
