### ISSUE TITLE
Fetch on 'end' is called before on 'message' finishes

### ISSUE THREAD

**Issue by francisco4challenge** [mscdex/node-imap#657]
Hey i'm trying to get Promises working with this but i'm having some trouble.
Why is the fetch 'end' being called before the end of on 'message'? 

```js
async function getEmails(
    imap: Imap,
    subject: string
): Promise<Email[]> {
    return new Promise<Email[]>((resolve, reject) => {
        const emails: Email[] = [];
        imap.openBox('INBOX', (err, box) => {
            if (err) {
                return reject(err);
            }
            imap.search(['UNSEEN', ['SUBJECT', subject]], (err, uids) => {
                const f = imap.fetch(uids, { bodies: [''] });

                f.on('message', async function (msg, seqno) {
                    const message = await processMessage(msg, seqno);
                    console.log(JSON.stringify(message, null, 2));
                    emails.push(message);
                });

                f.on('end', () => {
                    console.log('fetch end');
                    resolve(emails);
                });
            });
        });
    });
}
`
`
function processMessage(
    msg: Imap.ImapMessage,
    seqno: number
): Promise<Email> {
    return new Promise<Email>((resolve, reject) => {

        let email: Email = {
            body: '',
            to: '',
            from: '',
            date: null,
            id: seqno.toString(),
            subject: ''
        }
        const parser = new mailParser.MailParser();
        parser.on("headers", function (headers) {
            email.subject = headers.get('subject').toString();
            email.to = headers.get('to').toString();
            email.from = headers.get('from').toString();
            email.date = headers.get('date').valueOf() as Date;
        });

        parser.on('data', data => {
            if (data.type === 'text') {
                email.body = data.text;
                resolve(email);
            }
        });

        parser.on('end', (parsed) => {
        });

        msg.on("body", function (stream) {
            stream.on("data", function (chunk) {
                parser.write(chunk.toString("utf8"));
            });
        });

        msg.once("end", function () {
            parser.end();
        });
    });
}
```

Thanks in advance!

**Comment by mscdex** [comment]
The message emitter returned by `fetch()` does not track body streams.

`'end'` is emitted once the end of the response is seen, so that usually means that the last body stream has the last chunk buffered in memory at that point FWIW, so if the data is not being constantly read then you may end up with the message emitter's `'end'` before the body stream's `'end'`.

**Comment by francisco4challenge** [comment]
Then how could i make it wait for the body streams? Also what do you mean by, ' if the data is not being constantly read' ?

**Comment by mscdex** [comment]
For now you'd have to keep a counter around or similar which is incremented on a new body stream and decremented when the stream ends. If it's zero after decrementing and you're seen the message emitter's `'end'` event, then there should be no more streams.

What I meant by 'if the data is not being constantly read' is if you are not emptying the contents of the stream's internal buffer (either implicitly or explicitly depending on how you're using the body stream), then it could end up that the message emitter's `'end'` event fires too early because the body stream will not emit `'end'` until both the stream is closed _and_ the stream's internal buffer is empty (that is a general node stream behavior).

**Comment by francisco4challenge** [comment]
Thanks, quick fix, i like it.

**Comment by WebbizAdmin** [comment]
@francisco4challenge Could you post your solution? might be a bit old but good for next people looking at the issue. Thanks.

**Comment by vigneshtharani** [comment]
Not able to fix this, when I get data from 'end' function it fires even message parse is not completed. First runs end function and then message is parsing, please help this.

Thanks in advance!
