### ISSUE TITLE
imap.connect() not connected ready, only connecting: true

### ISSUE THREAD

**Issue by emclab** [mscdex/node-imap#741]
I am copying the example code to retrieve from gmail.com.  However the imap.connect() only has connecting: true and the connection was never ready. The node version is 10.13.0. Is the node version too new for the imap module?
![capture](https://user-images.githubusercontent.com/946013/50790202-20107800-1273-11e9-91fe-8a55963dbf4d.JPG)

const imap = new Imap({
  user: 'myemail@gmail.com',
  password: 'mypassword',
  port: 993,
  tls: true
});

function openInbox(callback) {
    imap.openBox('INBOX', true, callback);
};

async function parse_email(body) {
  let parsed = simpleParser(body);
};

imap.once('ready', function() {
  openInbox(function(err, box) {
    if (err) throw err;
    var f = imap.seq.fetch('1:3', {
      bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE)',
      struct: true
    });
    f.on('message', function(msg, seqno) {
      console.log('Message #%d', seqno);
      var prefix = '(#' + seqno + ') ';
      msg.on('body', function(stream, info) {
        var buffer = '';
        stream.on('data', function(chunk) {
          buffer += chunk.toString('utf8');
        });
        stream.once('end', function() {
          console.log(prefix + 'Parsed header: %s', inspect(Imap.parseHeader(buffer)));
        });
      });
      msg.once('attributes', function(attrs) {
        console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
      });
      msg.once('end', function() {
        console.log(prefix + 'Finished');
      });
    });
    f.once('error', function(err) {
      console.log('Fetch error: ' + err);
    });
    f.once('end', function() {
      console.log('Done fetching all messages!');
      imap.end();
    });
  });
});

imap.once('error', function(err) {
  console.log(err);
});

imap.once('end', function() {
  console.log('Connection ended');
});

imap.connect();

**Comment by mscdex** [comment]
What does/doesn't happen? Do you see an `'error'` event? Do you see the `'end'` event? The `'ready'` event?

If the connection is timing out, is there a firewall issue? You can test with a command line utility, like openssl: `openssl s_client -connect imap.gmail.com:993 -crlf`. If a successful connection is made you should see a bunch of output and especially a line at the end that starts with `* OK Gimap ready for requests from`

**Comment by emclab** [comment]
What are the variable values I can verify in debugger?

**Comment by mscdex** [comment]
You can set `debug: console.log` in your connection config.

However, can you also test with node v10.15.0?

Also, what does `npm ls --depth=0 | grep imap` show?

Lastly, is it possible that your program is being paused somehow since you're running within what seems to be an IDE? That might explain why the connection stays in the 'connecting' state and the connection timeout never fires (which defaults to 10 seconds). If you try running your script from a plain command/shell prompt (outside of any IDE), does it work there?

**Comment by emclab** [comment]
npm ls --depth=0 | grep imap shows:

+-- imap@0.8.19

and bunch of npm ERR. But none of them is related to imap module.

**Comment by emclab** [comment]
I am using Visual Studio Code IDE.

**Comment by mscdex** [comment]
Ah ok, so then it looks like something in the IDE is halting the process since we see the `'error'` and `'close'` events being emitted now when the script is ran from the command line.

As far as the error itself goes, it looks like someone/something is MITM'ing (intercepting) your connection to the server as the SSL/TLS certificate is not recognized as having been created by any of node's built-in list of trusted certificate authorities. This typically happens when the certificate is self-signed.

**Comment by emclab** [comment]
For the first certificate error, I tested imap.gmail.com on www.ssllabs.com and it return "Unable to connect to the server". Im confused by this message. Does it indicate the problem on the server?

**Comment by mscdex** [comment]
Probably because they are trying port 443. Most sites like that either assume port 443 and/or do not allow custom ports, such as 993. Other SSL/TLS checking services such as https://www.digicert.com/help or https://sslanalyzer.comodoca.com allow you to specify a custom port (e.g. `imap.gmail.com:993`).

I'm also curious what the certificate chain looks like from your side, can you show the output from `openssl s_client -showcerts -connect imap.gmail.com:993`? I'm wondering if the self-signed certificate is installed in the system OpenSSL certificate store, which node does not use by default, and that is why the openssl CLI is able to connect without the cert problem.

**Comment by emclab** [comment]
Here is the output of the openssl. All certs are self signed by Avast antivirus. But I did not recall generating those Avast certs. 
$ openssl s_client -showcerts -connect imap.gmail.com:993
CONNECTED(000001BC)
depth=0 OU = "No SNI provided; please fix your client.", CN = invalid2.invalid
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = "No SNI provided; please fix your client.", CN = invalid2.invalid
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/OU=No SNI provided; please fix your client./CN=invalid2.invalid
   i:/OU=generated by Avast Antivirus for self-signed certificates/O=Avast Web/Mail Shield/CN=Avast Web/Mail Shield Self-signed Root
-----BEGIN CERTIFICATE-----
....
lTFCMEAGA1UECww5Z2VuZXJhdGVkIGJ5IEF2YXN0IEFudGl2aXJ1cyBmb3Igc2Vs
Zi1zaWduZWQgY2VydGlmaWNhdGVzMR4wHAYDVQQKDBVBdmFzdCBXZWIvTWFpbCBT
AQoCggEBALRBsKEY0pqPCWEqU03nAf/UBeLiiPU4h0ODs9dwl/6iUT6aMXlCtGUv
...
-----END CERTIFICATE-----
 1 s:/OU=generated by Avast Antivirus for SSL/TLS scanning/O=Avast Web/Mail Shield/CN=Avast Web/Mail Shield Root
   i:/OU=generated by Avast Antivirus for SSL/TLS scanning/O=Avast Web/Mail Shield/CN=Avast Web/Mail Shield Root
-----BEGIN CERTIFICATE-----
....
Ka/fWoV6PuvHSjDy0HhpT9n/iEooOPtcmo4FIuCX7IXP8AJblienxO5MyT6M/Ljp
Jp0XtaGUhrj/R/HP494A2Gr5BRL8Fd8z+7uIRAsDjPevVO6XpTFy0Bi489pX6Qfz
ojgwHwYDVR0jBBgwFoAUKbbni8LPxYi9TZyxA6/UZnErojgwDQYJKoZIhvcNAQEL
...
-----END CERTIFICATE-----
---
Server certificate
subject=/OU=No SNI provided; please fix your client./CN=invalid2.invalid
issuer=/OU=generated by Avast Antivirus for self-signed certificates/O=Avast Web/Mail Shield/CN=Avast Web/Mail Shield Self-signed Root
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2663 bytes and written 434 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256
    Session-ID: 877FA7B923C00E4324F08E
    Session-ID-ctx:
    Master-Key: 816592D75.......EA
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 2a 41 fb 16 2f 99 03 c5-74 81 55 35 16 56 c1 8e   *A../...t.U5.V..
    0010 - 0b 90 2a e3 a7 af 57 bc-00 69 77 5c 08 30 0f 4f   ..*...W..iw\.0.O
......

    Start Time: 1546982920
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
* OK Gimap ready for requests from 65.78.160.67 e14mb749644634ocb

**Comment by emclab** [comment]
The imap.gmail.com:993 on digicert.com generated healthy report. :443 did not work.

**Comment by mscdex** [comment]
Alright, there's the answer then. Your Avast Antivirus is MITM'ing IMAP connections.

If you trust your Avast Antivirus to do this, then you can supply their certificates when connecting so that node can recognize/trust the certificate. You should be able to pass the certificates in the chain (shown in the openssl CLI output) with something like:

```js
const imap = new Imap({
  user: 'myemail@gmail.com',
  password: 'mypassword',
  port: 993,
  tls: true,
  tlsOptions: {
    ca: `-----BEGIN CERTIFICATE-----
....
lTFCMEAGA1UECww5Z2VuZXJhdGVkIGJ5IEF2YXN0IEFudGl2aXJ1cyBmb3Igc2Vs
Zi1zaWduZWQgY2VydGlmaWNhdGVzMR4wHAYDVQQKDBVBdmFzdCBXZWIvTWFpbCBT
AQoCggEBALRBsKEY0pqPCWEqU03nAf/UBeLiiPU4h0ODs9dwl/6iUT6aMXlCtGUv
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
....
Ka/fWoV6PuvHSjDy0HhpT9n/iEooOPtcmo4FIuCX7IXP8AJblienxO5MyT6M/Ljp
Jp0XtaGUhrj/R/HP494A2Gr5BRL8Fd8z+7uIRAsDjPevVO6XpTFy0Bi489pX6Qfz
ojgwHwYDVR0jBBgwFoAUKbbni8LPxYi9TZyxA6/UZnErojgwDQYJKoZIhvcNAQEL
...
-----END CERTIFICATE-----`
  }
});
```

**Comment by emclab** [comment]
You are right that Avast is the middle man. The error disappears after disable the mail shield in Avast setting. I can also choose to add the CA as you recommend. Your advice works very well to pin point the problem which has haunted me for days. Thank you for the help.

**Comment by mscdex** [comment]
Make sure the entire content of the certificates are in there back-to-back like in my example, as my code won't work as-is (obviously). You could also try setting `ca` to an array containing each certificate string (including the begin and end markers), although node supposedly supports multiple certificates in a single string. Otherwise if formatting or something else is causing problems, you could try saving each to a separate file and then reading them both with `fs.readFileSync()` into an array for `ca`.

If none of that works, try posting an issue on the https://github.com/nodejs/help/issues repo since setting `ca` should work (it completely overrides the built-in CA list).
