### ISSUE TITLE
How to get UUID after new mail receives

### ISSUE THREAD

**Issue by vigneshtharani** [mscdex/node-imap#755]
imap.on('mail', function (mail){
         console.log("New message arrived: ", mail);
});

In console always returns number of mail received, how to get UUID of new message returns inside this mail function?

**Comment by Enniya** [comment]
+1

**Comment by mscdex** [comment]
You could `imap.search()` for messages matching the `'NEW'` criteria. That will return messages that have the 'Recent' flag set but not the 'Seen' flag.

**Comment by vigneshtharani** [comment]
imap.search([ 'NEW'],
              function(err, results) {
                console.log(results, '+++resultss+++');
          });

Tried with this results return empty!

**Comment by mscdex** [comment]
`'NEW'` will only work if you search after receiving new email messages within the same session/connection. Is that the case? If you are reconnecting (or re-opening the mailbox) and searching with that criteria, it will not work and you will need to use a different criteria because the 'Recent' flag only applies to messages new to the session.
