### ISSUE TITLE
Empty header search critera not working

### ISSUE THREAD

**Issue by Kombustor** [mscdex/node-imap#770]
Hello,

I'm trying to search for all emails with the "List-Unsubscribe" header set, regardless what it's set to. According to the documentation:
> Requires two string values, with the first being the header name and the second being the value to search for. If this second string is empty, all messages that contain the given header name will be returned.

So my search criteria is:
```[['HEADER', 'LIST-UNSUBSCRIBE', '']]``` 

But all emails are returned, not just the ones with the List-Unsubscribe header.

Am I doing anything wrong?

**Comment by mscdex** [comment]
Can you set `debug: console.log` and post just line that contains the `SEARCH` request? Generally speaking though, the behavior is stated by RFC 3501. If servers deviate from that, then that is their problem, there isn't really anything this module can do about it.

**Comment by Kombustor** [comment]
The debug info is:
```'A6 UID SEARCH HEADER "LIST-UNSUBSCRIBE" ""'```

**Comment by mscdex** [comment]
Looks fine to me. One potential workaround might be able to simply do something like `[[ 'HEADER', 'LIST-UNSUBSCRIBE', ':' ]]` since such headers usually contain at least a colon as part of the unsubscribe link, be it `mailto:`, `http:`/`https:`, etc. However I believe I have seen gmail have issues with header text searching as well, so YMMV.
